apiVersion: apps/v1
kind: Deployment
metadata:
  name: fox-plugin-coin
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fox-plugin-coin
  template:
    metadata:
      labels:
        app: fox-plugin-coin
    spec:
      containers:
      - name: fox-plugin-coin
        image: uhub.service.ucloud.cn/entropypool/fox-plugin:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: host-config
            mountPath: /tmp/hosts
            subPath: .pluginproxyconfig
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENV_PROXY
          valueFrom:
            configMapKeyRef:
              name: fox-plugin-coin-environment
              key: environment.proxy
        - name: ENV_SYNC_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: fox-plugin-coin-environment
              key: environment.sync_interval
        - name: ENV_POSITION
          valueFrom:
            configMapKeyRef:
              name: fox-plugin-coin-environment
              key: environment.position
        command: ["/bin/sh", "-c", "cat /tmp/hosts >> /etc/hosts && /usr/local/bin/fox-plugin run"]
      volumes:
        - name: host-config
          configMap:
            name: pluginproxyconfig
